source: .
url: 'https://redash.io'
collections:
  data_sources:
    output: true
    permalink: /data-sources/:path
  partners:
    output: true
    permalink: /integrations/:path
  integrations:
    output: true
    permalink: /data-sources/:path
  docs:
    output: true
    permalink: /docs/:path/
gems:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-sitemap
